### ISSUE TITLE
Confirm box and Prompt box

### ISSUE THREAD

**Issue by arti0798** [krshrimali/Multi-Messenger#2]
Hey there, I, m trying to excute this code but getting undefine reference for confirm and prompt in .py file.
How can I resolve this?

**Comment by arti0798** [comment]
@krshrimali  @codacy-badger  @krutikabapat 
Hey there, I had resolved the prompt function but I m still struck with confirm function.

**Comment by arti0798** [comment]
@krshrimali  @codacy-badger  @krutikabapat 
please help me with confirm function.

**Comment by krshrimali** [comment]
Hi, @arti0798

Thank you for the ping and patience. Sorry for delay in responding.

This code was written 5 years back, and might be outdated. I would say, make sure that you can import `pyautogui` in a separate python shell. Also, if you can share the output of:

```bash
>>> import pyautogui
>>> help(pyautogui.confirm)
>>> help(pyautogui.prompt)
```

Make sure that each one of these commands work without any error in a Python shell. If they do, please share the output of:

```
>>> import pyautogui
>>> pyautogui.__version__
```

If it doesn't, then you need to install pyautogui on your system.

Thanks!

**Comment by arti0798** [comment]
@krshrimali  thanks for your help.
installation of pyautogui worked for me.
